api:
  build: api
  container_name: oak_hollow_api
  volumes:
    - ./api/lib/:/app/lib/
    - ./data/:/data/

    - ./api/app.psgi:/app/app.psgi
    - ./api/cpanfile:/app/cpanfile

  ports:
    - "8597:80"

front:
  build: front
  container_name: oak_hollow_front
  volumes:
    - ./front/:/app/

  ports:
    - "3576:8000"

nginx:
  image: nginx:1.10.1
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - api
    - front
  ports:
    - "3527:80"
